name: CD — Deploy LangGraph Backend

on:
  workflow_run:
    workflows: ["CI — Test Python Backend"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/langgraph-backend:latest
            ghcr.io/${{ github.repository_owner }}/langgraph-backend:${{ github.sha }}

      - name: Deploy using Python script
        env:
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
          IMAGE: ghcr.io/${{ github.repository_owner }}/langgraph-backend:${{ github.sha }}
        run: |
          echo "🚀 Installing dependencies for deploy script..."
          pip install requests
          python deploy_langgraph.py

      - name: Output info
        run: |
          echo "✅ Docker image built and deployment attempted."
          echo "Check the above logs for deployment status or endpoint details."
